//
// Created by puff on 2023-01-17.
//

#ifndef THECHERNOCPP_EP64_ND_ARRAY_IN_CPP_ND_ARRAY_IN_CPP_HPP_
#define THECHERNOCPP_EP64_ND_ARRAY_IN_CPP_ND_ARRAY_IN_CPP_HPP_

#endif //THECHERNOCPP_EP64_ND_ARRAY_IN_CPP_ND_ARRAY_IN_CPP_HPP_

void nd_array_in_cpp_main();