#include <iostream>
#include "Math.hpp"
#include "ep_test/test_file.hpp"
#include "ep16_pointer_tutorial/pointer_tutorial.hpp"
#include "ep17_ref_turtorial/ref_tutorial.hpp"
#include "ep18_class_in_cpp/class_in_cpp.hpp"
#include "ep20_first_class/first_class.hpp"
#include "ep21_static_in_cpp/static_in_cpp.hpp"
#include "ep22_struct_in_cls_and_struct/struct_in_cls_and_struct.hpp"
#include "ep24_constructors_in_cpp/constructors_in_cpp.hpp"
#include "ep26_inheritance_in_cpp/inheritance_in_cpp.hpp"
#include "ep27_virtual_func_in_cpp/virtual_func_in_cpp.hpp"
#include "ep28_interface_pure_function/interface_pure_function.hpp"
#include "ep29_visibility_in_cpp/visibility_in_cpp.h"
#include "ep30_array_in_cpp/array_in_cpp.hpp"
#include "ep31_string_in_cpp/string_in_cpp.hpp"
#include "ep32_string_literals_in_cpp/string_literals_in_cpp.hpp"
#include "ep33_const_in_cpp/const_in_cpp.hpp"
#include "ep34_mutable_kw_in_cpp/mutable_kw_in_cpp.hpp"
#include "ep35_member_init_ls_in_cpp/member_init_ls_in_cpp.hpp"
#include "ep36_ternary_ops_in_cpp/ternary_ops_in_cpp.hpp"
#include "ep37_create_instantiate_obj/create_instantiate_obj.hpp"
#include "ep40_op_overload_in_cpp/op_overload_in_cpp.hpp"
#include "ep42_obj_lifetime_in_cpp/obj_lifetime_in_cpp.hpp"
#include "ep43_smart_ptr_in_cpp/smart_ptr_in_cpp.hpp"
#include "ep44_copy_constructor/copy_constructor.hpp"
#include "ep45_arrow_op/arrow_op.hpp"
#include "ep46_dynamic_arr/dynamic_arr.hpp"
#include "ep47_vector_optmz/vector_optmz.hpp"
#include "ep48_local_static_in_cpp/local_static_in_cpp.hpp"
#include "ep53_template_in_cpp/template_in_cpp.hpp"
#include "ep55_macros_in_cpp/macros_in_cpp.hpp"

int main() {
//  test_main();
//  pointer_tutorial_main();
//  ref_tutorial_main();
//  class_in_cpp_main();
//  first_class_main();
//  struct_in_cls_and_struct_main();
//  constructor_in_cpp_main();
//  inheritance_in_cpp_main();
//  virtual_func_in_cpp();
//  string_in_cpp_main();
//  string_literals_in_cpp();
//  const_in_cpp_main();
//  mutable_kw_in_cpp();
//  member_init_ls_in_cpp_main();
//  ternary_ops_in_cpp_main();
//  create_instantiate_obj_main();
//  op_overload_in_cpp_main();
//  obj_lifetime_in_cpp();
//  smart_ptr_in_cpp_main();
//  copy_constructor_main();
//  arrow_op_main();
//  dynamic_arr_main();
//  vector_optimize_main();
//  local_static_in_cpp_main();
//  template_in_cpp_main();
  macros_in_cpp_main();

  return 0;
}
