//
// Created by puff on 2023-01-16.
//

#ifndef THECHERNOCPP_EP62_THREADS_IN_CPP_THREADS_IN_CPP_HPP_
#define THECHERNOCPP_EP62_THREADS_IN_CPP_THREADS_IN_CPP_HPP_

#endif //THECHERNOCPP_EP62_THREADS_IN_CPP_THREADS_IN_CPP_HPP_

void threads_in_cpp_main();