//
// Created by puff on 2023-01-17.
//

#ifndef THECHERNOCPP_EP63_TIMING_IN_CPP_TIMING_IN_CPP_HPP_
#define THECHERNOCPP_EP63_TIMING_IN_CPP_TIMING_IN_CPP_HPP_

#endif //THECHERNOCPP_EP63_TIMING_IN_CPP_TIMING_IN_CPP_HPP_

void timing_in_cpp_main();